"""empty message

Revision ID: 06b7744ed46d
Revises: f2b72933aca9
Create Date: 2023-08-01 08:55:27.657390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b7744ed46d'
down_revision = 'f2b72933aca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('planets_name_key', ['name'])

    # ### end Alembic commands ###
